#!/usr/bin/env bash
# Emit a filled `.env` for the Langfuse prod stack (CHO-286).
#
# Every secret is generated here rather than typed, because the failure mode of
# hand-picked values is silent: upstream's compose defaults (`mysalt`,
# `miniosecret`) are published in a public repo and would still start cleanly.
#
#   ./gen-secrets.sh > .env     # then fill the two ADMIN fields it leaves blank
#
# Run it ONCE per install. Re-running mints new values, and changing SALT /
# ENCRYPTION_KEY / NEXTAUTH_SECRET after first boot invalidates existing API
# keys, stored secrets, and sessions respectively.
set -euo pipefail

command -v openssl >/dev/null || { echo "openssl not found" >&2; exit 1; }

b64() { openssl rand -base64 32 | tr -d '\n'; }
hex() { openssl rand -hex 32 | tr -d '\n'; }
# Password-safe: no '/', '+' or '=' to trip up DSN parsing or shell quoting.
pw()  { openssl rand -hex 24 | tr -d '\n'; }
uuid() {
  if command -v uuidgen >/dev/null; then uuidgen | tr 'A-Z' 'a-z' | tr -d '\n'
  else openssl rand -hex 16 | sed -E 's/(.{8})(.{4})(.{4})(.{4})(.{12})/\1-\2-\3-\4-\5/' | tr -d '\n'
  fi
}

cat <<EOF
# Generated by deploy/langfuse/gen-secrets.sh — DO NOT COMMIT.
# See .env.example for what each value does.

POSTGRES_PASSWORD=$(pw)
CLICKHOUSE_PASSWORD=$(pw)
REDIS_AUTH=$(pw)
MINIO_ROOT_PASSWORD=$(pw)

SALT=$(b64)
ENCRYPTION_KEY=$(hex)
NEXTAUTH_SECRET=$(b64)
NEXTAUTH_URL=http://localhost:3000

# Copy these two into /home/harsh/jini/.env as
# LANGFUSE_PUBLIC_KEY / LANGFUSE_SECRET_KEY.
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-$(uuid)
LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-$(uuid)

# >>> FILL THESE IN — the compose file refuses to start while they are blank.
LANGFUSE_INIT_USER_EMAIL=
LANGFUSE_INIT_USER_PASSWORD=$(pw)
LANGFUSE_INIT_USER_NAME=Jini Admin

LANGFUSE_INIT_ORG_ID=choice
LANGFUSE_INIT_ORG_NAME=Choice
LANGFUSE_INIT_PROJECT_ID=jini
LANGFUSE_INIT_PROJECT_NAME=Choice Jini
EOF
