"""Freshdesk escalation core + /api/ticket route (CHO-218 · tasks 1.1-1.4).

Everything here is hermetic: the Freshdesk API is respx-mocked on a fake
host, and every credential-shaped value (API key, JWT, session id) is a
test-only placeholder — NOT a real credential. No live Freshdesk call is
ever made from this suite.
"""

import asyncio
import base64
import json

import httpx
import pytest
import respx
from fastapi.testclient import TestClient

from app import config
from app.agent.ctx import CODE_UPSTREAM_ERROR, CODE_VALIDATION, ToolCtx, ToolError
from app.agent.store import ThreadStore
from app.agent.tickets import (
    render_transcript,
    run_raise_ticket,
    ticket_call_is_user_initiated,
    ticket_memo,
)
from app.main import create_app

SESSION_ID = "ticket-session-token"  # test placeholder, not a real session
SSO_JWT = "test-sso-jwt-not-real"  # test placeholder, not a real JWT
CLIENT_CODE = "X008593"

HEADERS = {
    "Authorization": SSO_JWT,
    "X-Session-Id": SESSION_ID,
    "X-User-Id": CLIENT_CODE,
}

# Fake Freshdesk endpoint — respx intercepts everything aimed at it.
FD_ROOT = "https://fd-test.invalid/api/v2"
FD_KEY = "fd-test-key"  # NOT a real credential — mocked-API placeholder


def _fd_env(monkeypatch):
    monkeypatch.setenv("FRESHDESK_API_ROOT", FD_ROOT)
    monkeypatch.setenv("FRESHDESK_API_KEY", FD_KEY)


# --- thread scaffolding -------------------------------------------------------


def _thread(turns=()):
    """Memory-only thread; (role, kind, content) triples appended in order."""
    store = ThreadStore()
    thread = asyncio.run(store.get_thread(SESSION_ID, client_code=CLIENT_CODE))
    for role, kind, content in turns:
        store.append_turn(thread, role=role, kind=kind, content=content)
    return thread


def _text(text):
    return [{"type": "text", "text": text}]


# --- CHO-241: user-initiated ticket guard ------------------------------------


def test_explicit_escalation_request_is_user_initiated():
    for phrase in (
        "please raise a ticket",
        "raise a complaint about this",
        "connect me to a human",
        "I want to talk to an agent",
        "can you escalate this",
    ):
        thread = _thread([("user", "user_text", _text(phrase))])
        assert ticket_call_is_user_initiated(thread), phrase


def test_affirmative_after_an_offer_is_user_initiated():
    thread = _thread([
        ("user", "user_text", _text("my withdrawal is stuck")),
        ("assistant", "assistant_text", _text(
            "Want me to raise a ticket so the team can take this up?"
        )),
        ("user", "user_text", _text("yes please")),
    ])
    assert ticket_call_is_user_initiated(thread)


def test_preemptive_ticket_is_not_user_initiated():
    thread = _thread([("user", "user_text", _text("what are the DP charges?"))])
    assert not ticket_call_is_user_initiated(thread)


def test_affirmative_without_a_prior_offer_is_not_user_initiated():
    thread = _thread([("user", "user_text", _text("yes"))])
    assert not ticket_call_is_user_initiated(thread)


def _conversation_thread():
    """A conversation with tool internals that must NEVER reach the ticket."""
    return _thread([
        ("user", "user_text", _text("my report password doesn't work")),
        (
            "assistant",
            "assistant_tool_use",
            [{
                "type": "tool_use",
                "id": "tu_1",
                "name": "search_knowledge_base",
                "input": {"query": "report pdf password"},
            }],
        ),
        (
            "user",
            "tool_result",
            [{
                "type": "tool_result",
                "tool_use_id": "tu_1",
                # Header-shaped strings planted to prove exclusion: the
                # renderer must never leak tool_result content.
                "content": json.dumps({
                    "kind": "ok",
                    "sessionId": SESSION_ID,
                    "jwt": SSO_JWT,
                }),
                "is_error": False,
            }],
        ),
        ("assistant", "assistant_text", _text("Use your PAN in capitals.")),
        (
            "user",
            "flow_event",
            _text("[App event — generated by the app, not typed by the user] "
                  "The user completed the P&L form in the widget — "
                  "downloaded successfully."),
        ),
    ])


# --- transcript renderer (design D2) -----------------------------------------


def test_transcript_includes_conversation_and_excludes_tool_internals():
    out = render_transcript(
        _conversation_thread(), reason="Password problem", client_code=CLIENT_CODE
    )

    # metadata block
    assert f"<b>Client ID:</b> {CLIENT_CODE}" in out
    assert "<b>Reason:</b> Password problem" in out
    assert "<b>Raised at:</b>" in out
    assert "<b>Turns included:</b> 3 of 3" in out

    # the conversation, speaker-labelled; app events italicized
    assert "<b>Client:</b> my report password doesn&#x27;t work" in out
    assert "<b>Jini:</b> Use your PAN in capitals." in out
    assert "<i>[App event" in out

    # NEVER tool internals or header-shaped values (spec: credential scan)
    assert SESSION_ID not in out
    assert SSO_JWT not in out
    assert "tool_use" not in out
    assert "tool_result" not in out
    assert "search_knowledge_base" not in out
    assert "tu_1" not in out


def test_transcript_html_escapes_text():
    thread = _thread([
        ("user", "user_text", _text('<script>alert("x")</script> & more')),
    ])
    out = render_transcript(thread, reason="R & D <test>", client_code=CLIENT_CODE)
    assert "<script>" not in out
    assert "&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt; &amp; more" in out
    assert "<b>Reason:</b> R &amp; D &lt;test&gt;" in out


def test_transcript_truncates_oldest_first_past_turn_cap():
    thread = _thread([
        ("user", "user_text", _text(f"message {i}")) for i in range(120)
    ])
    out = render_transcript(thread, reason="General Query", client_code=CLIENT_CODE)
    assert "<b>Turns included:</b> 100 of 120" in out
    assert "showing the last 100 of 120 turns" in out
    assert "message 119" in out  # newest kept
    assert "message 19" not in out and "message 0</p>" not in out  # oldest gone


def test_transcript_truncates_past_byte_soft_cap():
    big = "a" * 20_000
    thread = _thread([
        ("user", "user_text", _text(f"{i}-{big}")) for i in range(5)
    ])
    out = render_transcript(thread, reason="General Query", client_code=CLIENT_CODE)
    assert len(out.encode("utf-8")) <= 60_000
    assert "<b>Turns included:</b> 2 of 5" in out
    assert f"4-{big}" in out  # the newest tail survives


def test_transcript_skips_empty_turns_and_tolerates_no_thread():
    thread = _thread([
        ("user", "user_text", _text("")),  # empty — skipped
        ("user", "user_text", _text("real question")),
    ])
    out = render_transcript(thread, reason="General Query", client_code=CLIENT_CODE)
    assert "<b>Turns included:</b> 1 of 1" in out
    # Defensive: no thread at all still renders a metadata-only description.
    empty = render_transcript(None, reason="General Query", client_code=CLIENT_CODE)
    assert "<b>Turns included:</b> 0 of 0" in empty


def test_ticket_memo_is_app_event_framed():
    memo = ticket_memo(7551234, "need a human")
    assert memo == (
        "[App event — generated by the app, not typed by the user] "
        "Support ticket #7551234 raised — need a human."
    )


# --- ticket core: payload contract (design D1) --------------------------------


def _ctx(http_client, thread=None):
    return ToolCtx(
        session_id=SESSION_ID,
        sso_jwt=SSO_JWT,
        client_code=CLIENT_CODE,
        http_client=http_client,
        thread=thread,
    )


async def _run(params, thread=None):
    async with httpx.AsyncClient() as http:
        return await run_raise_ticket(params, _ctx(http, thread=thread))


@respx.mock
def test_payload_matches_the_cloned_contract(monkeypatch):
    _fd_env(monkeypatch)
    route = respx.post(f"{FD_ROOT}/tickets").mock(
        return_value=httpx.Response(201, json={"id": 7551234, "status": 2})
    )
    result = asyncio.run(
        _run({"reason": "General Query"}, thread=_conversation_thread())
    )
    assert result == {"kind": "ticket", "ticketId": 7551234, "status": "Open"}

    request = route.calls.last.request
    sent = json.loads(request.content)
    description = sent.pop("description")
    # Byte-for-byte the D1 parameter set — requester is the client code only,
    # no email/phone fields anywhere.
    assert sent == {
        "subject": f"[Choice Jini] General Query — Client {CLIENT_CODE}",
        "unique_external_id": CLIENT_CODE,
        "name": CLIENT_CODE,
        "status": 2,
        "priority": 2,
        "source": 7,
        "type": "GENERAL QUERY",
        "group_id": 22000168676,
        "tags": ["choice-jini", "chatbot-testing", "lang:en"],
        "custom_fields": {
            "cf_client_id": CLIENT_CODE,
            "cf_source": "chat box",
            "cf_product": "finx",
            "cf_query_type149508": "finx-bot",
            "cf_query_sub_type": "finx-bot-test",
        },
    }
    assert "email" not in sent and "phone" not in sent
    # description = the transcript, credential-clean
    assert "<b>Client:</b>" in description
    assert SESSION_ID not in description and SSO_JWT not in description
    # basic auth: API key + "X", never logged, never in the body
    expected = base64.b64encode(f"{FD_KEY}:X".encode()).decode()
    assert request.headers["authorization"] == f"Basic {expected}"
    assert FD_KEY not in request.content.decode()


def test_group_id_env_override(monkeypatch):
    assert config.freshdesk_group_id() == 22000168676
    monkeypatch.setenv("FRESHDESK_GROUP_ID", "12345")
    assert config.freshdesk_group_id() == 12345


def test_api_root_built_from_domain(monkeypatch):
    # Hermetic against the developer's real .env: _secret falls back to the
    # root env file when the process env lacks the key, so kill the fallback.
    monkeypatch.setattr(config, "_root_env_value", lambda key: None)
    monkeypatch.delenv("FRESHDESK_API_ROOT", raising=False)
    monkeypatch.setenv("FRESHDESK_DOMAIN", "choiceindia")
    assert config.freshdesk_api_root() == "https://choiceindia.freshdesk.com/api/v2"
    monkeypatch.setenv("FRESHDESK_API_ROOT", f"{FD_ROOT}/")
    assert config.freshdesk_api_root() == FD_ROOT  # explicit root wins; no trailing /


# --- ticket core: failure posture (design D4) ---------------------------------


@pytest.mark.parametrize("status", [400, 429, 500, 502])
@respx.mock
def test_upstream_failure_is_tool_error_never_a_stub(monkeypatch, status):
    _fd_env(monkeypatch)
    respx.post(f"{FD_ROOT}/tickets").mock(return_value=httpx.Response(status))
    result = asyncio.run(_run({"reason": "General Query"}))
    assert isinstance(result, ToolError)
    assert result.code == CODE_UPSTREAM_ERROR
    assert "Help section" in result.message


@respx.mock
def test_timeout_is_tool_error(monkeypatch):
    _fd_env(monkeypatch)
    respx.post(f"{FD_ROOT}/tickets").mock(
        side_effect=httpx.ConnectTimeout("timed out")
    )
    result = asyncio.run(_run({"reason": "General Query"}))
    assert isinstance(result, ToolError)
    assert result.code == CODE_UPSTREAM_ERROR


def test_unconfigured_freshdesk_is_tool_error_without_a_call(monkeypatch):
    monkeypatch.delenv("FRESHDESK_API_ROOT", raising=False)
    monkeypatch.delenv("FRESHDESK_DOMAIN", raising=False)
    monkeypatch.delenv("FRESHDESK_API_KEY", raising=False)
    with respx.mock:  # no routes mocked — an attempted call would fail loudly
        result = asyncio.run(_run({"reason": "General Query"}))
        assert isinstance(result, ToolError)
        assert result.code == CODE_UPSTREAM_ERROR
        assert not respx.calls  # nothing left the process


def test_reason_is_validated(monkeypatch):
    _fd_env(monkeypatch)
    for params in ({}, {"reason": ""}, {"reason": "x" * 201}):
        result = asyncio.run(_run(params))
        assert isinstance(result, ToolError)
        assert result.code == CODE_VALIDATION


@respx.mock
def test_extra_params_are_ignored_not_honored(monkeypatch):
    """Smuggled identity fields never reach the payload (registry contract)."""
    _fd_env(monkeypatch)
    route = respx.post(f"{FD_ROOT}/tickets").mock(
        return_value=httpx.Response(201, json={"id": 1})
    )
    result = asyncio.run(
        _run({"reason": "hi", "unique_external_id": "EVIL01", "email": "a@b.c"})
    )
    assert result == {"kind": "ticket", "ticketId": 1, "status": "Open"}
    sent = json.loads(route.calls.last.request.content)
    assert sent["unique_external_id"] == CLIENT_CODE
    assert "EVIL01" not in route.calls.last.request.content.decode()
    assert "a@b.c" not in route.calls.last.request.content.decode()


# --- POST /api/ticket (task 1.4) ----------------------------------------------


@pytest.fixture()
def app(monkeypatch):
    monkeypatch.setattr("app.config.database_url", lambda: None)  # memory-only
    return create_app()


def _store_thread(app):
    store = app.state.conversation_store
    return asyncio.run(store.get_thread(SESSION_ID, client_code=CLIENT_CODE))


def test_ticket_route_requires_credentials(app):
    with TestClient(app) as client:
        resp = client.post("/api/ticket", json={"reason": "General Query"})
    assert resp.status_code == 400
    assert resp.json() == {"error": "MISSING_CREDENTIALS"}


@respx.mock
def test_ticket_route_success_appends_memo(app, monkeypatch):
    _fd_env(monkeypatch)
    route = respx.post(f"{FD_ROOT}/tickets").mock(
        return_value=httpx.Response(201, json={"id": 7551234})
    )
    with TestClient(app) as client:
        thread = _store_thread(app)
        app.state.conversation_store.append_turn(
            thread, role="user", kind="user_text",
            content=_text("the report is wrong"),
        )
        resp = client.post(
            "/api/ticket", headers=HEADERS, json={"reason": "General Query"}
        )
        assert resp.status_code == 200
        assert resp.json() == {"ticketId": 7551234, "status": "Open"}

        # the conversation travelled in the description
        sent = json.loads(route.calls.last.request.content)
        assert "the report is wrong" in sent["description"]
        # the flow-event memo landed on the thread
        memo = thread.turns[-1]
        assert memo.kind == "flow_event"
        assert memo.content[0]["text"] == ticket_memo(7551234, "General Query")
        assert memo.meta == {
            "flow": "ticket", "reason": "General Query", "ticketId": 7551234,
        }


@respx.mock
def test_ticket_route_defaults_reason_without_body(app, monkeypatch):
    _fd_env(monkeypatch)
    route = respx.post(f"{FD_ROOT}/tickets").mock(
        return_value=httpx.Response(201, json={"id": 42})
    )
    with TestClient(app) as client:
        resp = client.post("/api/ticket", headers=HEADERS)
        assert resp.status_code == 200
        assert resp.json() == {"ticketId": 42, "status": "Open"}
    sent = json.loads(route.calls.last.request.content)
    assert sent["subject"] == f"[Choice Jini] General Query — Client {CLIENT_CODE}"


@respx.mock
def test_ticket_route_upstream_failure_is_error_json_no_memo(app, monkeypatch):
    _fd_env(monkeypatch)
    respx.post(f"{FD_ROOT}/tickets").mock(return_value=httpx.Response(500))
    with TestClient(app) as client:
        resp = client.post(
            "/api/ticket", headers=HEADERS, json={"reason": "General Query"}
        )
        assert resp.status_code == 502
        assert resp.json() == {"error": "UPSTREAM_ERROR"}
        thread = _store_thread(app)
        assert [t.kind for t in thread.turns] == []  # no memo, no stub id
