"""Read-time context curation (CHO-271 · tasks 4.1-4.14, 4.16).

Everything here is pure: threads are built through the real `ThreadStore`
(memory-only, so content/meta are canonicalized exactly as in production) and
no model, DB or clock is involved. The properties under test are the ones the
whole scheme rests on — the `tool_use`/`tool_result` pairing survives, the
watermark is monotone and within-turn stable, the store is never mutated, and
no renderer can physically read a currency amount.
"""

import json
import re

import pytest

from app import config
from app.agent import curation, tickets
from app.agent.store import Thread, ThreadStore

STORE = ThreadStore(pool=None)  # memory-only: canonicalizes, never persists

FRAME = "[App note — generated by the app, not typed by the user]"


# --- thread builders ----------------------------------------------------------


def _thread() -> Thread:
    return Thread(id="thread-1", session_id="session-1")


def _user(thread, text="hello"):
    return STORE.append_turn(
        thread, role="user", kind="user_text",
        content=[{"type": "text", "text": text}],
    )


def _assistant(thread, text="here you go"):
    return STORE.append_turn(
        thread, role="assistant", kind="assistant_text",
        content=[{"type": "text", "text": text}],
    )


def _tool_use(thread, *uses):
    """uses: (tool_use_id, name) pairs — one assistant_tool_use turn."""
    return STORE.append_turn(
        thread, role="assistant", kind="assistant_tool_use",
        content=[
            {"type": "tool_use", "id": uid, "name": name, "input": {}}
            for uid, name in uses
        ],
    )


def _result(
    thread, tool, envelope=None, *, raw=None, is_error=False, tool_use_id="tu_1"
):
    content = (
        raw
        if raw is not None
        else json.dumps(envelope or {}, sort_keys=True, separators=(",", ":"))
    )
    return STORE.append_turn(
        thread, role="user", kind="tool_result",
        content=[
            {
                "type": "tool_result",
                "tool_use_id": tool_use_id,
                "content": content,
                "is_error": is_error,
            }
        ],
        meta={"tool_name": tool, "is_error": is_error, "duration_ms": 4},
    )


def _flow_event(thread, text="[App event] something happened."):
    return STORE.append_turn(
        thread, role="user", kind="flow_event",
        content=[{"type": "text", "text": text}],
    )


def _stub_text(turn):
    blocks = curation.stub_blocks(turn)
    assert blocks is not None, "expected this turn to be curatable"
    return blocks[0]["content"]


def _region_json(thread, *, upto_seq):
    """Serialize the curated projection restricted to turns with seq <=
    upto_seq, using the CURRENT watermark's transform. The head thread shares
    the real thread's memo dict through the closure."""
    transform = curation.curate(thread)
    head = Thread(id=thread.id, session_id=thread.session_id)
    head.turns = [t for t in thread.turns if t.seq <= upto_seq]
    return json.dumps(head.messages(transform=transform), separators=(",", ":"))


# --- realistic envelopes (shapes taken from the flow cores) ------------------

HOLDINGS_OK = {
    "kind": "ok",
    "asOf": "2026-07-25T15:30:00",
    "rows": [
        {
            "Sym": "TCS", "Name": "Tata Consultancy", "Q": 10, "ABP": 3100.0,
            "LTP": 3250.5, "CP": 3240.0, "current": 32505.0,
            "invested": 31000.0, "pnl": 1505.0, "day": 105.0, "alloc": 27.1,
        }
    ] * 12,
    "totals": {
        "count": 12, "current": 120000.0, "invested": 100000.0, "pnl": 20000.0,
        "pnlPct": 20.0, "day": 500.0, "dayPct": 0.4,
    },
}

MONEY_OK = {
    "kind": "ok",
    "txns": [
        {
            "dir": "in", "amt": 5000.0, "st": "Success", "dt": "2026-07-01T10:00:00",
            "mode": "UPI", "dest": "HDFC ****1234", "ref": "V123", "rsn": None,
        }
    ] * 72,
    "counts": {"Success": 70, "Failed": 2},
    "landed": {"in": 500000.0, "out": 100000.0},
    "totalRecords": {"in": 40, "out": 32},
    "partial": False,
}

MONEY_PARTIAL = {
    "kind": "ok",
    "txns": [{"dir": "in", "amt": 5000.0, "st": "Success"}] * 3,
    "counts": {"Success": 3},
    "landed": {"in": 15000.0, "out": 0.0},
    "totalRecords": {"in": 3, "out": 0},
    "partial": True,
}

BROKERAGE_OK = {
    "kind": "ok",
    "groups": [
        {
            "title": "Equity Delivery",
            "list": [{"title": "Brokerage", "desc": "₹20 per executed order"}],
        }
    ] * 4,
}

FILE_DOWNLOAD = {
    "delivery": "download",
    "file": {
        "name": "PnL_Equity_2025-04-01_to_2026-03-31.pdf",
        "sizeLabel": "182 KB", "format": "PDF", "passwordProtected": True,
    },
    "fileToken": "tok_abc123",
    "ttlSeconds": 900,
    "expiresAt": "2026-07-25T10:15:00+00:00",
}

FILE_EMAIL = {"delivery": "email", "emailMasked": "san***@gmail.com"}

NOTE_DOWNLOAD = {
    "delivery": "download",
    "file": {
        "name": "Contract_Note_03Apr2025.pdf", "sizeLabel": "44 KB",
        "format": "PDF", "passwordProtected": False,
    },
    "fileToken": "tok_note",
}

KB_OK = {
    "kind": "ok",
    "results": [
        {
            "id": 1, "topic": "Funds", "section": "Payin",
            "question": "How do I add funds to my trading account?",
            "answer": "Transfer via UPI or NEFT; ₹0 charges apply.",
            "tat": "T+1", "score": 0.031,
        },
        {
            "id": 2, "topic": "Funds", "section": "Payout",
            "question": "How long does a withdrawal take?",
            "answer": "Payouts settle T+1 working day.",
            "tat": None, "score": 0.028,
        },
    ],
}

COLUMNS_OK = {
    "report": "ledger",
    "title": "Ledger / account statement",
    "note": "Amounts are in INR.",
    "columns": [{"label": "Voucher No", "gloss": "The voucher reference."}] * 9,
    "ambiguousLabels": ["Amount"],
}


def _notes(n):
    return {
        "notes": [
            {
                "id": f"cn_{i:03d}",
                "date": f"{(i % 28) + 1} Apr 2025",
                "segment": "Equity" if i % 2 else "F&O",
                "badge": None,
                "month": "April 2025",
            }
            for i in range(n)
        ]
    }


# --- 4.1 golden stub string per renderer --------------------------------------

GOLDEN = [
    (
        "get_holdings", HOLDINGS_OK,
        f"{FRAME} get_holdings result cleared. The holdings card rendered in "
        "the chat with 12 holdings (value, invested, P&L and day change shown "
        "to the user). The figures are no longer in this transcript — call "
        "get_holdings again if you need them.",
    ),
    (
        "get_holdings", {"kind": "empty"},
        f"{FRAME} get_holdings result cleared. The user had no holdings; the "
        "empty-state card rendered in the chat. Call get_holdings again to "
        "check whether that is still true.",
    ),
    (
        "get_money_transactions", MONEY_OK,
        f"{FRAME} get_money_transactions result cleared. The money-movements "
        "card rendered in the chat with 72 pay-in/pay-out transactions for the "
        "current financial year. The figures are no longer in this transcript "
        "— call get_money_transactions again if you need them.",
    ),
    (
        "get_money_transactions", MONEY_PARTIAL,
        f"{FRAME} get_money_transactions result cleared. The money-movements "
        "card rendered in the chat with 3 pay-in/pay-out transactions for the "
        "current financial year. One direction was unavailable for that card. "
        "The figures are no longer in this transcript — call "
        "get_money_transactions again if you need them.",
    ),
    (
        "get_money_transactions", {"kind": "empty"},
        f"{FRAME} get_money_transactions result cleared. The user had no money "
        "movements this financial year; the empty-state card rendered in the "
        "chat. Call get_money_transactions again if you need the current list.",
    ),
    (
        "get_brokerage_rates", BROKERAGE_OK,
        f"{FRAME} get_brokerage_rates result cleared. The brokerage rate card "
        "rendered in the chat with 4 rate groups. The rates are no longer in "
        "this transcript — call get_brokerage_rates again if you need them.",
    ),
    (
        "get_pnl_report", FILE_DOWNLOAD,
        f"{FRAME} get_pnl_report result cleared. The file "
        "PnL_Equity_2025-04-01_to_2026-03-31.pdf was delivered in the chat as "
        "a download card. The download link is no longer in this transcript — "
        "call get_pnl_report again if the user wants it re-sent.",
    ),
    (
        "get_ledger_report", FILE_EMAIL,
        f"{FRAME} get_ledger_report result cleared. The report was sent to the "
        "user's registered email, as confirmed in the chat. Call "
        "get_ledger_report again if the user wants it re-sent.",
    ),
    (
        "download_contract_note", NOTE_DOWNLOAD,
        f"{FRAME} download_contract_note result cleared. The file "
        "Contract_Note_03Apr2025.pdf was delivered in the chat as a download "
        "card. The download link is no longer in this transcript — call "
        "download_contract_note again if the user wants it re-sent.",
    ),
    (
        "search_knowledge_base", KB_OK,
        f"{FRAME} search_knowledge_base result cleared, matched questions "
        "kept. The search above returned 2 support answers, which you already "
        "used in your reply — How do I add funds to my trading account?; How "
        "long does a withdrawal take?. The answer text is no longer in this "
        "transcript — call search_knowledge_base again if the user follows up "
        "on any of them.",
    ),
    (
        "get_report_columns", COLUMNS_OK,
        f"{FRAME} get_report_columns result cleared. The column list for the "
        "ledger report (9 columns) was returned and you already used it. The "
        "labels are no longer in this transcript — call get_report_columns "
        "again before describing any report column.",
    ),
    (
        "list_contract_notes", _notes(0),
        f"{FRAME} list_contract_notes result cleared. No contract notes exist "
        "for the range in the call above. Call list_contract_notes again with "
        "a different range if the user asks.",
    ),
    (
        # legacy / unparseable envelope for a REGISTERED tool -> generic
        "get_holdings", {},
        f"{FRAME} get_holdings result cleared. Its result was already "
        "delivered to the user; the data is no longer in this transcript — "
        "call get_holdings again if you need it.",
    ),
]


@pytest.mark.parametrize("tool,envelope,expected", GOLDEN)
def test_golden_stub_per_renderer(tool, envelope, expected):
    thread = _thread()
    _user(thread)
    turn = _result(thread, tool, envelope)
    assert _stub_text(turn) == expected


def test_brokerage_empty_state_stub():
    thread = _thread()
    _user(thread)
    turn = _result(thread, "get_brokerage_rates", {"kind": "empty"})
    assert _stub_text(turn) == (
        f"{FRAME} get_brokerage_rates result cleared. No rate card was "
        "available for this client; the empty-state card rendered in the chat. "
        "Call get_brokerage_rates again if you need it."
    )


def test_money_empty_states_the_partial_direction():
    thread = _thread()
    _user(thread)
    turn = _result(
        thread, "get_money_transactions", {"kind": "empty", "partial": True}
    )
    text = _stub_text(turn)
    assert "One direction was unavailable for that card." in text
    # The recovery clause still comes LAST — the abstention fix depends on it.
    assert text.endswith("Call get_money_transactions again if you need the current list.")


def test_kb_stub_with_no_results_still_offers_a_recovery():
    thread = _thread()
    _user(thread)
    turn = _result(thread, "search_knowledge_base", {"kind": "ok", "results": []})
    assert _stub_text(turn) == (
        f"{FRAME} search_knowledge_base result cleared. The search above "
        "returned no usable support answers. Call search_knowledge_base again "
        "with a different query if the user follows up."
    )


def test_kb_stub_drops_answer_tat_and_score_keeps_questions():
    thread = _thread()
    _user(thread)
    text = _stub_text(_result(thread, "search_knowledge_base", KB_OK))
    assert "How do I add funds to my trading account?" in text
    assert "Payouts settle" not in text
    assert "T+1" not in text
    assert "0.031" not in text


def test_kb_stub_shrinks_a_realistic_top_k_envelope():
    """The shipped audit measured ~940 -> ~120 tok on a real `top_k=10`
    envelope. Assert the direction on a realistic one, not the exact ratio."""
    envelope = {
        "kind": "ok",
        "results": [
            {
                "id": i,
                "topic": "Funds",
                "section": "Payin",
                "question": f"How do I do support thing number {i}?",
                "answer": (
                    "Open the app, go to Funds, choose the account and follow "
                    "the on-screen steps. Charges may apply depending on the "
                    "mode you pick; settlement is on the next working day. "
                ) * 3,
                "tat": "T+1",
                "score": 0.03 - i / 1000,
            }
            for i in range(10)
        ],
    }
    thread = _thread()
    _user(thread)
    text = _stub_text(_result(thread, "search_knowledge_base", envelope))
    verbatim = json.dumps(envelope, sort_keys=True, separators=(",", ":"))
    assert len(text) * 4 < len(verbatim)
    for i in range(10):
        assert f"support thing number {i}?" in text


def test_columns_stub_drops_the_labels_too():
    """REPORT COLUMNS RULE: keeping labels would invite describing a column
    from its label alone, so the stub carries the count only."""
    thread = _thread()
    _user(thread)
    text = _stub_text(_result(thread, "get_report_columns", COLUMNS_OK))
    assert "Voucher No" not in text
    assert "The voucher reference." not in text
    assert "9 columns" in text
    assert text.endswith(
        "call get_report_columns again before describing any report column."
    )


def test_file_email_stub_never_echoes_the_masked_email():
    thread = _thread()
    _user(thread)
    text = _stub_text(_result(thread, "get_ledger_report", FILE_EMAIL))
    assert "san***@gmail.com" not in text
    assert "@" not in text


def test_file_download_stub_never_echoes_the_file_token():
    thread = _thread()
    _user(thread)
    text = _stub_text(_result(thread, "get_pnl_report", FILE_DOWNLOAD))
    assert "tok_abc123" not in text


def test_every_renderer_ends_with_an_actionable_recovery_clause():
    """Task 1.9 / the single most important design property: a stub must never
    read as a bare absence claim — that wording is what INDUCES abstention."""
    cases = [(tool, env) for tool, env, _ in GOLDEN]
    cases += [
        ("get_brokerage_rates", {"kind": "empty"}),
        ("search_knowledge_base", {"kind": "ok", "results": []}),
        ("list_contract_notes", _notes(6)),
        ("list_contract_notes", _notes(45)),
        ("download_contract_note", FILE_EMAIL),
    ]
    for tool, envelope in cases:
        thread = _thread()
        _user(thread)
        text = _stub_text(_result(thread, tool, envelope))
        assert text.endswith("."), (tool, text)
        # names a tool to call again, in the final sentence
        last = text.rsplit(". ", 1)[-1]
        assert re.search(r"\bcall \w+\b", last, re.IGNORECASE), (tool, last)


# --- 4.2 only the content string changes -------------------------------------


def test_stub_preserves_type_tool_use_id_and_is_error():
    thread = _thread()
    _user(thread)
    turn = _result(thread, "get_holdings", HOLDINGS_OK, tool_use_id="tu_42")
    stored = turn.content[0]
    stub = curation.stub_blocks(turn)[0]
    assert stub["type"] == "tool_result" == stored["type"]
    assert stub["tool_use_id"] == "tu_42" == stored["tool_use_id"]
    assert stub["is_error"] is False is stored["is_error"]
    assert set(stub) == set(stored)
    assert list(stub) == list(stored)  # canonical key order preserved
    assert stub["content"] != stored["content"]
    assert len(stub["content"]) < len(stored["content"])


# --- 4.3 / 4.4 never-curate rules --------------------------------------------


@pytest.mark.parametrize(
    "tool",
    sorted(curation._RENDERERS)
    + sorted(curation._KEEP_VERBATIM)
    + ["totally_unknown_tool"],
)
def test_error_results_are_never_stubbed(tool):
    thread = _thread()
    _user(thread)
    turn = _result(
        thread, tool,
        raw="Call open_report_form instead — the dates are missing.",
        is_error=True,
    )
    assert curation.stub_blocks(turn) is None


@pytest.mark.parametrize("tool", sorted(curation._KEEP_VERBATIM))
def test_routing_and_state_results_are_never_stubbed(tool):
    thread = _thread()
    _user(thread)
    envelopes = {
        "open_report_form": {
            "kind": "form", "flow": "ledger",
            "seed": {"book": "MTF", "fromDate": "2026-04-01"},
            "prefilled": ["book", "fromDate"], "note": "widget will ask",
        },
        "raise_support_ticket": {
            "kind": "ticket", "ticketId": 991234, "status": "open",
        },
    }
    turn = _result(thread, tool, envelopes[tool])
    assert curation.stub_blocks(turn) is None
    # ... and the projection leaves it verbatim even many user turns later
    for _ in range(3):
        _user(thread, "another question")
    view = curation.messages_for_model(thread)
    flat = json.dumps(view)
    assert json.dumps(turn.content[0]["content"])[1:-1] in flat


def test_open_report_form_seed_survives_a_long_thread():
    """The routing exemplar this change exists to reinforce must reach the
    model verbatim, or curation is self-defeating."""
    thread = _thread()
    _user(thread, "ledger for MTF")
    _tool_use(thread, ("tu_1", "open_report_form"))
    _result(
        thread, "open_report_form",
        {"kind": "form", "flow": "ledger", "seed": {"book": "MTF"}},
    )
    _assistant(thread, "Opening the ledger form.")
    for i in range(4):
        _user(thread, f"unrelated {i}")
        _tool_use(thread, ("tu_h", "get_holdings"))
        _result(thread, "get_holdings", HOLDINGS_OK, tool_use_id="tu_h")
        _assistant(thread, "here are your holdings")
    _user(thread, "now the same for Normal")

    flat = json.dumps(curation.messages_for_model(thread))
    assert "\\\"flow\\\":\\\"ledger\\\"" in flat  # seed envelope still verbatim
    assert "get_holdings result cleared" in flat  # the noise IS gone


# --- 4.5 note ids ------------------------------------------------------------


def test_notes_stub_keeps_every_id_below_the_cap():
    thread = _thread()
    _user(thread)
    text = _stub_text(_result(thread, "list_contract_notes", _notes(6)))
    for i in range(6):
        assert f"cn_{i:03d} = " in text
    assert "6 contract notes were returned" in text
    assert "expire about 10 minutes after they were issued" in text
    assert text.endswith("if a download bounces, call list_contract_notes again.")
    assert "Older ids were dropped" not in text
    assert "April 2025" not in text  # month dropped
    assert '"badge"' not in text and "badge" not in text


def test_notes_stub_keeps_the_forty_newest_and_says_so():
    thread = _thread()
    _user(thread)
    text = _stub_text(_result(thread, "list_contract_notes", _notes(45)))
    assert "45 contract notes were returned" in text
    for i in range(5):  # the five oldest are gone
        assert f"cn_{i:03d} = " not in text
    for i in range(5, 45):  # the forty newest survive
        assert f"cn_{i:03d} = " in text
    assert text.count(" = ") == curation._MAX_NOTE_IDS == 40
    assert "expire about 10 minutes after they were issued" in text
    assert text.endswith(
        "Older ids were dropped — call list_contract_notes again with a "
        "narrower range if the user asks for one of those."
    )


def test_notes_stub_is_much_smaller_than_the_envelope():
    thread = _thread()
    _user(thread)
    envelope = _notes(20)
    verbatim = json.dumps(envelope, sort_keys=True, separators=(",", ":"))
    text = _stub_text(_result(thread, "list_contract_notes", envelope))
    assert len(text) < len(verbatim)


# --- 4.6 K=1 boundary --------------------------------------------------------


def test_k1_boundary_current_turn_verbatim_previous_turn_stubbed():
    thread = _thread()
    _user(thread, "what do I hold?")
    _tool_use(thread, ("tu_1", "get_holdings"))
    first = _result(thread, "get_holdings", HOLDINGS_OK)

    # Same turn: still verbatim (the continuation call needs the figures).
    view = curation.messages_for_model(thread)
    assert json.dumps(view).count("get_holdings result cleared") == 0
    assert view[-1]["content"][0]["content"] == first.content[0]["content"]

    _assistant(thread, "You hold 12 stocks.")
    _user(thread, "and my money movements?")
    _tool_use(thread, ("tu_2", "get_money_transactions"))
    second = _result(
        thread, "get_money_transactions", MONEY_OK, tool_use_id="tu_2"
    )

    view = curation.messages_for_model(thread)
    flat = json.dumps(view)
    assert "get_holdings result cleared" in flat  # previous turn: stubbed
    assert "get_money_transactions result cleared" not in flat  # this turn
    assert view[-1]["content"][0]["content"] == second.content[0]["content"]


def test_watermark_is_the_newest_user_text_seq():
    thread = _thread()
    assert curation.watermark(thread) == 0
    u1 = _user(thread, "one")
    assert curation.watermark(thread) == u1.seq
    _tool_use(thread, ("tu_1", "get_holdings"))
    _result(thread, "get_holdings", HOLDINGS_OK)
    _flow_event(thread)
    assert curation.watermark(thread) == u1.seq  # mid-turn appends do not move it
    u2 = _user(thread, "two")
    assert curation.watermark(thread) == u2.seq
    assert u2.seq > u1.seq  # monotone


# --- 4.7 monotonicity across turns -------------------------------------------


def test_pre_watermark_prefix_is_byte_identical_at_later_turns():
    thread = _thread()
    _user(thread, "turn one")
    _tool_use(thread, ("tu_1", "get_holdings"))
    _result(thread, "get_holdings", HOLDINGS_OK)
    _assistant(thread, "twelve holdings")
    mark = _user(thread, "turn two").seq  # W advances: turn one is now spent

    frozen = _region_json(thread, upto_seq=mark)

    for n, tool, envelope in (
        (3, "get_money_transactions", MONEY_OK),
        (4, "search_knowledge_base", KB_OK),
        (5, "list_contract_notes", _notes(6)),
    ):
        _tool_use(thread, (f"tu_{n}", tool))
        _result(thread, tool, envelope, tool_use_id=f"tu_{n}")
        _assistant(thread, f"answer {n}")
        _user(thread, f"turn {n}")
        assert _region_json(thread, upto_seq=mark) == frozen, f"changed at turn {n}"


# --- 4.8 within-turn byte stability ------------------------------------------


def test_prefix_through_newest_user_text_is_stable_across_rounds_of_one_turn():
    thread = _thread()
    _user(thread, "turn one")
    _tool_use(thread, ("tu_1", "get_holdings"))
    _result(thread, "get_holdings", HOLDINGS_OK)
    _assistant(thread, "twelve holdings")
    mark = _user(thread, "and my notes?").seq

    round_1 = _region_json(thread, upto_seq=mark)

    # round 2: a tool_result lands mid-turn
    _tool_use(thread, ("tu_2", "list_contract_notes"))
    _result(thread, "list_contract_notes", _notes(6), tool_use_id="tu_2")
    assert _region_json(thread, upto_seq=mark) == round_1
    assert curation.watermark(thread) == mark

    # round 3: another one, plus a flow_event memo
    _tool_use(thread, ("tu_3", "download_contract_note"))
    _result(thread, "download_contract_note", NOTE_DOWNLOAD, tool_use_id="tu_3")
    _flow_event(thread)
    assert _region_json(thread, upto_seq=mark) == round_1
    assert curation.watermark(thread) == mark


def test_projection_is_byte_identical_at_one_watermark():
    thread = _thread()
    _user(thread, "one")
    _tool_use(thread, ("tu_1", "get_holdings"))
    _result(thread, "get_holdings", HOLDINGS_OK)
    _assistant(thread, "ok")
    _user(thread, "two")
    first = json.dumps(curation.messages_for_model(thread))
    second = json.dumps(curation.messages_for_model(thread))
    assert first == second


# --- 4.9 / 4.10 fail-open, never raises --------------------------------------


def test_unregistered_tool_is_kept_verbatim():
    thread = _thread()
    _user(thread)
    turn = _result(thread, "get_market_clock_that_does_not_exist_yet", {"kind": "ok"})
    assert curation.stub_blocks(turn) is None
    _user(thread, "next")
    flat = json.dumps(curation.messages_for_model(thread))
    assert "result cleared" not in flat


def test_missing_tool_name_in_meta_is_kept_verbatim():
    thread = _thread()
    _user(thread)
    turn = STORE.append_turn(
        thread, role="user", kind="tool_result",
        content=[
            {
                "type": "tool_result", "tool_use_id": "tu_1",
                "content": '{"kind":"ok"}', "is_error": False,
            }
        ],
        meta={},  # legacy row: no tool_name at all
    )
    assert curation.stub_blocks(turn) is None


@pytest.mark.parametrize(
    "raw", ["{}", "not json at all", "[1,2,3]", "", "null", '{"kind":"weird"}']
)
def test_garbage_content_falls_back_to_the_generic_stub(raw):
    thread = _thread()
    _user(thread)
    turn = _result(thread, "get_money_transactions", raw=raw)
    text = _stub_text(turn)
    assert text == (
        f"{FRAME} get_money_transactions result cleared. Its result was "
        "already delivered to the user; the data is no longer in this "
        "transcript — call get_money_transactions again if you need it."
    )


def test_stub_blocks_never_raises_on_a_malformed_turn():
    class Broken:
        kind = "tool_result"
        seq = 3
        meta = {"tool_name": "get_holdings", "is_error": False}
        content = "not-a-list-of-blocks"

    assert curation.stub_blocks(Broken()) is None

    class NoMeta:
        kind = "tool_result"
        seq = 3
        meta = None
        content = []

    assert curation.stub_blocks(NoMeta()) is None
    assert curation.watermark(Thread(id="x", session_id="y")) == 0


# --- 4.11 the flag ------------------------------------------------------------


def test_flag_defaults_off(monkeypatch):
    monkeypatch.delenv("AGENT_CONTEXT_CURATION", raising=False)
    assert config.agent_context_curation() is False


@pytest.mark.parametrize("value", ["1", "true", "TRUE", "yes", "on", " on "])
def test_flag_truthy_values(monkeypatch, value):
    monkeypatch.setenv("AGENT_CONTEXT_CURATION", value)
    assert config.agent_context_curation() is True


@pytest.mark.parametrize("value", ["0", "false", "off", "no", "", "maybe"])
def test_flag_falsy_values(monkeypatch, value):
    monkeypatch.setenv("AGENT_CONTEXT_CURATION", value)
    assert config.agent_context_curation() is False


def test_no_transform_array_is_unchanged_by_curation():
    """The lossless default: `messages()` with no transform is byte-identical
    before and after the curated view has been built."""
    thread = _thread()
    _user(thread, "one")
    _tool_use(thread, ("tu_1", "get_holdings"))
    _result(thread, "get_holdings", HOLDINGS_OK)
    _assistant(thread, "ok")
    _user(thread, "two")

    before = json.dumps(thread.messages())
    curation.messages_for_model(thread)
    assert json.dumps(thread.messages()) == before


# --- 4.12 the store is never mutated or aliased ------------------------------


def test_store_turns_are_untouched_and_no_stub_aliases_a_stored_block():
    thread = _thread()
    _user(thread, "one")
    _tool_use(thread, ("tu_1", "get_holdings"))
    result_turn = _result(thread, "get_holdings", HOLDINGS_OK)
    _assistant(thread, "ok")
    _user(thread, "two")

    snapshot = [json.dumps(t.content) for t in thread.turns]
    view = curation.messages_for_model(thread)

    assert [json.dumps(t.content) for t in thread.turns] == snapshot
    assert result_turn.content[0]["content"] == json.dumps(
        HOLDINGS_OK, sort_keys=True, separators=(",", ":")
    )

    stored_ids = {id(block) for turn in thread.turns for block in turn.content}
    view_ids = {id(block) for message in view for block in message["content"]}
    stubbed = [
        b
        for message in view
        for b in message["content"]
        if isinstance(b.get("content"), str) and "result cleared" in b["content"]
    ]
    assert len(stubbed) == 1
    assert id(stubbed[0]) not in stored_ids

    # mutating the view can never reach the store or the memo cache
    stubbed[0]["content"] = "TAMPERED"
    assert [json.dumps(t.content) for t in thread.turns] == snapshot
    again = curation.messages_for_model(thread)
    assert "TAMPERED" not in json.dumps(again)
    assert view_ids  # sanity: the view really did carry blocks


def test_memoised_stub_is_not_handed_out_by_reference():
    thread = _thread()
    _user(thread, "one")
    _tool_use(thread, ("tu_1", "get_holdings"))
    turn = _result(thread, "get_holdings", HOLDINGS_OK)
    _user(thread, "two")

    first = curation.messages_for_model(thread)
    assert turn.seq in thread.curated  # memoised per seq
    second = curation.messages_for_model(thread)
    blocks_1 = [b for m in first for b in m["content"]]
    blocks_2 = [b for m in second for b in m["content"]]
    assert json.dumps(blocks_1) == json.dumps(blocks_2)
    assert all(id(a) != id(b) for a, b in zip(blocks_1, blocks_2) if "content" in a)


# --- 4.13 the key whitelist IS the currency guard ----------------------------

# Anything amount-, price-, identity-, token- or label-bearing that a stub must
# never be able to read. The guard is structural: these keys are absent from
# every whitelist, so no renderer can reach them even by mistake.
FORBIDDEN_KEYS = frozenset(
    {
        "amt", "landed", "counts", "totalRecords", "current", "invested",
        "pnl", "pnlPct", "day", "dayPct", "alloc", "ltp", "LTP", "abp", "ABP",
        "CP", "Q", "Sym", "Name", "rates", "desc", "title", "label", "gloss",
        "answer", "tat", "score", "fileToken", "emailMasked", "sizeLabel",
        "asOf", "badge", "month", "ambiguousLabels", "note", "seed",
        "prefilled", "st", "dt", "dest", "ref", "rsn", "mode", "rows", "list",
        "ticketId", "expiresAt", "ttlSeconds", "passwordProtected",
    }
)

# Count / length / customer-facing-label / date / id keys only.
ALLOWED_VOCABULARY = frozenset(
    {
        "kind", "totals", "count", "txns", "partial", "groups", "delivery",
        "file", "name", "results", "question", "report", "columns", "notes",
        "id", "date", "segment",
    }
)


def test_every_renderer_has_a_whitelist_and_vice_versa():
    assert set(curation._RENDERERS) == set(curation._ALLOWED_KEYS)


def test_no_whitelist_contains_an_amount_bearing_key():
    for tool, allowed in curation._ALLOWED_KEYS.items():
        assert not (allowed & FORBIDDEN_KEYS), (tool, allowed & FORBIDDEN_KEYS)
        assert allowed <= ALLOWED_VOCABULARY, (tool, allowed - ALLOWED_VOCABULARY)


def _keys_at_every_depth(value):
    if isinstance(value, dict):
        out = set(value)
        for item in value.values():
            out |= _keys_at_every_depth(item)
        return out
    if isinstance(value, list):
        out = set()
        for item in value:
            out |= _keys_at_every_depth(item)
        return out
    return set()


@pytest.mark.parametrize(
    "tool,envelope",
    [
        ("get_holdings", HOLDINGS_OK),
        ("get_money_transactions", MONEY_OK),
        ("get_brokerage_rates", BROKERAGE_OK),
        ("get_pnl_report", FILE_DOWNLOAD),
        ("get_ledger_report", FILE_EMAIL),
        ("download_contract_note", NOTE_DOWNLOAD),
        ("search_knowledge_base", KB_OK),
        ("get_report_columns", COLUMNS_OK),
        ("list_contract_notes", _notes(20)),
    ],
)
def test_pruned_view_carries_no_forbidden_key(tool, envelope):
    view = curation._prune(envelope, curation._ALLOWED_KEYS[tool])
    assert not (_keys_at_every_depth(view) & FORBIDDEN_KEYS)
    assert _keys_at_every_depth(view) <= ALLOWED_VOCABULARY


def test_data_stubs_carry_no_rupee_amount():
    """Asserted per renderer, not globally: real KB questions legitimately
    contain ₹ (FAQ rows about charges), so a blanket regex would be wrong."""
    thread = _thread()
    _user(thread)
    for tool, envelope in (
        ("get_holdings", HOLDINGS_OK),
        ("get_money_transactions", MONEY_OK),
        ("get_brokerage_rates", BROKERAGE_OK),
        ("get_report_columns", COLUMNS_OK),
        ("get_pnl_report", FILE_DOWNLOAD),
    ):
        text = _stub_text(_result(thread, tool, envelope))
        assert "₹" not in text, tool
        assert "20000" not in text and "3250.5" not in text, tool
        assert "TCS" not in text, tool


# --- 4.14 tool_use / tool_result pairing -------------------------------------


def test_parallel_round_pairing_survives_curation():
    thread = _thread()
    _user(thread, "holdings, money and my notes")
    _tool_use(
        thread,
        ("tu_a", "get_holdings"),
        ("tu_b", "get_money_transactions"),
        ("tu_c", "list_contract_notes"),
    )
    _result(thread, "get_holdings", HOLDINGS_OK, tool_use_id="tu_a")
    _result(thread, "get_money_transactions", MONEY_OK, tool_use_id="tu_b")
    _result(thread, "list_contract_notes", _notes(6), tool_use_id="tu_c")
    _assistant(thread, "all three, done")
    _user(thread, "thanks — and the ledger?")

    view = curation.messages_for_model(thread)
    use_ids = [
        b["id"]
        for m in view
        for b in m["content"]
        if b.get("type") == "tool_use"
    ]
    result_ids = [
        b["tool_use_id"]
        for m in view
        for b in m["content"]
        if b.get("type") == "tool_result"
    ]
    assert sorted(use_ids) == ["tu_a", "tu_b", "tu_c"]
    assert sorted(result_ids) == sorted(use_ids)
    assert len(result_ids) == len(set(result_ids))

    # one merged user message, tool_result blocks FIRST (the API requires it)
    merged = next(
        m
        for m in view
        if m["role"] == "user"
        and any(b.get("type") == "tool_result" for b in m["content"])
    )
    types = [b["type"] for b in merged["content"]]
    assert types == ["tool_result"] * 3
    assert all("result cleared" in b["content"] for b in merged["content"])

    # same block count as the lossless array — nothing dropped, nothing added
    lossless = thread.messages()
    assert [len(m["content"]) for m in view] == [len(m["content"]) for m in lossless]


def test_flow_event_memo_still_partitions_after_the_results():
    thread = _thread()
    _user(thread, "raise a ticket please")
    _tool_use(thread, ("tu_t", "raise_support_ticket"))
    _result(
        thread, "raise_support_ticket",
        {"kind": "ticket", "ticketId": 5, "status": "open"}, tool_use_id="tu_t",
    )
    _flow_event(thread, "[App event] Support ticket #5 raised — login issue.")
    _user(thread, "what is the status?")

    view = curation.messages_for_model(thread)
    merged = next(
        m
        for m in view
        if m["role"] == "user"
        and any(b.get("type") == "tool_result" for b in m["content"])
    )
    assert [b["type"] for b in merged["content"]] == [
        "tool_result", "text", "text",
    ]


# --- 4.16 ticket transcript + affirmation guard are unaffected ---------------


_RAISED_AT = re.compile(r"<b>Raised at:</b>[^<]*<br>")


def _transcript(thread):
    return _RAISED_AT.sub(
        "<b>Raised at:</b> FROZEN<br>",
        tickets.render_transcript(thread, reason="cannot log in", client_code="X1"),
    )


def test_ticket_transcript_and_guard_are_identical_with_and_without_curation():
    """Both read `thread.turns`, never the view — so building the projection
    must not be observable to them."""
    thread = _thread()
    _user(thread, "I cannot log in")
    _tool_use(thread, ("tu_1", "get_holdings"))
    _result(thread, "get_holdings", HOLDINGS_OK)
    _assistant(thread, "Want me to raise a ticket so the team can take this up?")
    _user(thread, "yes please")

    before_transcript = _transcript(thread)
    before_guard = tickets.ticket_call_is_user_initiated(thread)

    curation.messages_for_model(thread)  # build the curated view

    assert _transcript(thread) == before_transcript
    assert tickets.ticket_call_is_user_initiated(thread) is before_guard is True
    # tool_result envelopes were never in the transcript to begin with
    assert "get_holdings" not in before_transcript
    assert "result cleared" not in before_transcript


# --- observability counts ----------------------------------------------------


def test_curated_turn_count_and_history_estimate():
    thread = _thread()
    assert curation.curated_turn_count(thread) == 0
    _user(thread, "one")
    _tool_use(thread, ("tu_1", "get_holdings"))
    _result(thread, "get_holdings", HOLDINGS_OK)
    _result(thread, "raise_support_ticket", {"kind": "ticket"}, tool_use_id="tu_2")
    _result(thread, "get_pnl_report", raw="boom", is_error=True, tool_use_id="tu_3")
    assert curation.curated_turn_count(thread) == 0  # nothing spent yet
    _user(thread, "two")
    # only the holdings result is curatable (ticket + error are never curated)
    assert curation.curated_turn_count(thread) == 1

    lossless = curation.history_tokens_est(thread.messages())
    curated = curation.history_tokens_est(curation.messages_for_model(thread))
    assert 0 < curated < lossless
    assert curation.history_tokens_est([]) == 0  # deterministic, never raises
    assert curation.history_tokens_est([{"role": "user", "content": object()}]) > 0
