"""Flow-event memory tests (CHO-214 · tasks 3.1/3.2): deterministic memo,
fire-and-forget write, and total isolation from the report response path."""

import asyncio
from types import SimpleNamespace

from app.agent.events import friendly_range, record_flow_event, render_memo
from app.agent.store import ThreadStore


# --- memo renderer -----------------------------------------------------------


def test_memo_is_deterministic_and_framed():
    memo = render_memo(
        "pnl", ["Equity", friendly_range("2026-06-01", "2026-06-30")], "download"
    )
    assert memo == (
        "[App event — generated by the app, not typed by the user] "
        "The user completed the P&L form in the widget: Equity, "
        "1 Jun – 30 Jun 2026 (2026-06-01 → 2026-06-30) — "
        "downloaded successfully."
    )
    # Byte-stable across calls — the stored text IS the wire text.
    assert memo == render_memo(
        "pnl", ["Equity", friendly_range("2026-06-01", "2026-06-30")], "download"
    )


def test_memo_email_outcome_and_no_details():
    memo = render_memo("tax", [], "email")
    assert "capital gains form" in memo
    # No details → no colon; the outcome attaches directly to "widget".
    assert "widget — sent to the registered email." in memo


def test_friendly_range_cross_year_and_invalid():
    assert friendly_range("2025-12-15", "2026-01-15") == (
        "15 Dec 2025 – 15 Jan 2026 (2025-12-15 → 2026-01-15)"
    )
    assert friendly_range("junk", "2026-01-15") == "junk → 2026-01-15"


# --- fire-and-forget write ---------------------------------------------------


def _fake_app(store):
    return SimpleNamespace(state=SimpleNamespace(conversation_store=store))


def test_record_appends_flow_event_turn():
    async def main():
        store = ThreadStore()  # memory-only
        record_flow_event(
            _fake_app(store),
            session_id="s1",
            client_code="X008593",
            flow="pnl",
            details=["Equity", friendly_range("2026-06-01", "2026-06-30")],
            slots={
                "segment": "Equity",
                "fromDate": "2026-06-01",
                "toDate": "2026-06-30",
            },
            delivery="download",
        )
        await asyncio.sleep(0.01)  # let the fire-and-forget task run
        thread = await store.get_thread("s1", client_code="X008593")
        assert len(thread.turns) == 1
        turn = thread.turns[0]
        assert turn.role == "user"
        assert turn.kind == "flow_event"
        assert turn.content[0]["type"] == "text"
        assert "[App event" in turn.content[0]["text"]
        assert turn.meta["flow"] == "pnl"
        assert turn.meta["outcome"] == "success"
        assert turn.meta["slots"]["segment"] == "Equity"

    asyncio.run(main())


def test_record_without_store_is_a_noop():
    record_flow_event(  # no state.conversation_store, no running loop
        SimpleNamespace(state=SimpleNamespace()),
        session_id="s1",
        client_code=None,
        flow="pnl",
        details=[],
        slots={},
        delivery="download",
    )


def test_record_swallows_store_failure():
    class ExplodingStore:
        async def get_thread(self, *a, **k):
            raise RuntimeError("db down")

    async def main():
        record_flow_event(
            _fake_app(ExplodingStore()),
            session_id="s1",
            client_code=None,
            flow="ledger",
            details=["Normal book"],
            slots={"book": "Normal"},
            delivery="email",
        )
        await asyncio.sleep(0.01)  # task runs, failure logged, nothing raises

    asyncio.run(main())


def test_memo_carries_no_credentials():
    memo = render_memo(
        "ledger", ["Normal book", friendly_range("2026-06-01", "2026-06-30")], "email"
    )
    for needle in ("token", "Bearer", "SessionId", "http"):
        assert needle not in memo
