"""Read-time context curation (CHO-271) — spent tool_result payloads → stubs.

Measured on a representative 15-turn widget session, 91.3% of the model-facing
history is `tool_result` content and only 1.8% is the user's own words. That
distractor mass is the documented long-context failure mode for Claude:
**abstention** — answering "that was not provided in the chat history" about a
fact that IS present. This module removes the mass.

It is a **pure read-time projection**, nothing more:

  * The lossless store is NEVER mutated. Every function here is a pure function
    of stored `content` bytes plus `Turn.meta` — no clock, no model call, no
    request state — so replay, ticket transcripts, derived counters, feedback
    anchors and the training corpus are untouched by construction.
  * Only the `content` **string** of a *spent* `tool_result` block is replaced.
    `type`, `tool_use_id` and `is_error` are copied through unchanged: the
    Messages API 400s on a `tool_use` block with no matching `tool_result`, so
    dropping or reordering blocks is not an option at any K.
  * Every stub ends with an **actionable recovery clause naming the tool to
    call again**. A bare "data removed" placeholder is precisely the wording
    most likely to *induce* the abstention failure this module exists to fix.
  * Stubs carry counts, customer-facing labels, dates and opaque ids only —
    never ₹ amounts, prices, scrip names, file tokens, credentials, masked
    contact values or raw upstream fields. This is enforced structurally by the
    per-renderer key whitelist in `_ALLOWED_KEYS` (a renderer physically cannot
    read a key it was not granted), not by an output regex.

Boundary: the **watermark** `W` is the `seq` of the newest `user_text` turn. A
`tool_result` turn is curated iff `turn.seq < W` and its class rules allow it.
`W` depends on `user_text` turns only — mid-turn appends are `tool_result` and
`flow_event` — so it cannot move between rounds of one turn, it only ever
increases, and the stub text is byte-deterministic. K is therefore pinned to 1
per class, in code: verbatim inside its own turn, stubbed from the next user
message onward. There is deliberately no env knob for K.

Never curated: any result with `meta["is_error"] is True` (the error text IS
the corrective instruction), `open_report_form` and `raise_support_ticket` (the
routing/state exemplars this change exists to reinforce), and any tool with no
registered renderer (**fail-open** — adding a tool must never silently degrade
context).
"""

import json
from typing import Any, Callable

from app.agent.store import Thread, Turn

# Mirrors the shipped app-event memo frame (`app/agent/events.py:25`) with a
# distinct noun, so a curation note is never read as an app *event* (something
# the user did in the widget).
_FRAME = "[App note — generated by the app, not typed by the user]"

# Routing / state exemplars: 69-110 tok and ~38 tok measured. The
# open_report_form envelope (flow + seed + prefilled) is the strongest
# in-context exemplar of the exact behaviour curation exists to restore.
_KEEP_VERBATIM = frozenset({"open_report_form", "raise_support_ticket"})

# list_contract_notes ids are ascending by trade date; keep the newest N.
_MAX_NOTE_IDS = 40

_FILE_TOOLS = frozenset(
    {
        "get_pnl_report",
        "get_ledger_report",
        "get_capital_gains_report",
        "download_contract_note",
    }
)


# --- key whitelist (the currency/PII guard, enforced structurally) -----------
#
# Before a renderer runs, the parsed envelope is pruned to these keys at EVERY
# depth. A renderer therefore cannot read an amount, a price, a scrip name, a
# file token or a masked email even by mistake: the key is simply not there.
# Container keys (`txns`, `groups`, `columns`, `results`, `notes`) survive with
# their items emptied, so only the LENGTH of a list is readable.
_ALLOWED_KEYS: dict[str, frozenset[str]] = {
    # kind ("ok"/"empty") + totals.count. rows (Sym/Name/Q/ABP/LTP/CP, alloc)
    # and every totals figure (current/invested/pnl/pnlPct/day/dayPct) dropped.
    "get_holdings": frozenset({"kind", "totals", "count"}),
    # kind + len(txns) + the partial flag. Each txn is emptied (amt/st/dt/mode/
    # dest/ref/rsn gone); counts, landed and totalRecords dropped wholesale.
    "get_money_transactions": frozenset({"kind", "txns", "partial"}),
    # kind + len(groups). Group titles and rate descriptions dropped.
    "get_brokerage_rates": frozenset({"kind", "groups"}),
    # delivery + file.name. fileToken, ttlSeconds, expiresAt, sizeLabel,
    # format, passwordProtected and (crucially) emailMasked all dropped.
    "get_pnl_report": frozenset({"delivery", "file", "name"}),
    "get_ledger_report": frozenset({"delivery", "file", "name"}),
    "get_capital_gains_report": frozenset({"delivery", "file", "name"}),
    "download_contract_note": frozenset({"delivery", "file", "name"}),
    # kind + the matched question strings. answer / tat / score / topic /
    # section / id dropped (topic is the reserved enrichment lever).
    "search_knowledge_base": frozenset({"kind", "results", "question"}),
    # report key + len(columns). Labels and glosses dropped deliberately: the
    # REPORT COLUMNS RULE mandates answering only from a fresh call.
    "get_report_columns": frozenset({"report", "columns"}),
    # every id with its date and segment. badge / month dropped.
    "list_contract_notes": frozenset({"notes", "id", "date", "segment"}),
}


# --- helpers -----------------------------------------------------------------


def _prune(value: Any, allowed: frozenset[str]) -> Any:
    """Recursively keep only whitelisted keys, at every depth. Lists keep their
    length (items are pruned in place), which is all any renderer needs."""
    if isinstance(value, dict):
        return {k: _prune(v, allowed) for k, v in value.items() if k in allowed}
    if isinstance(value, list):
        return [_prune(item, allowed) for item in value]
    return value


def _count(value: Any) -> int | None:
    return len(value) if isinstance(value, list) else None


def _label(value: Any) -> str | None:
    """A stored customer-facing label, whitespace-collapsed to keep the stub a
    single deterministic line. Non-strings and blanks become None."""
    if not isinstance(value, str):
        return None
    text = " ".join(value.split())
    return text or None


def _generic(tool: str) -> str:
    """Fallback for a registered tool whose envelope is legacy ("{}"), not
    JSON, or shaped in a way no renderer recognises."""
    return (
        f"{_FRAME} {tool} result cleared. Its result was already delivered to "
        f"the user; the data is no longer in this transcript — call {tool} "
        "again if you need it."
    )


# --- renderers (envelope view -> stub text; None => generic fallback) --------


def _render_holdings(view: dict) -> str | None:
    kind = view.get("kind")
    if kind == "empty":
        return (
            f"{_FRAME} get_holdings result cleared. The user had no holdings; "
            "the empty-state card rendered in the chat. Call get_holdings "
            "again to check whether that is still true."
        )
    if kind != "ok":
        return None
    count = (view.get("totals") or {}).get("count")
    if not isinstance(count, int):
        return None
    return (
        f"{_FRAME} get_holdings result cleared. The holdings card rendered in "
        f"the chat with {count} holdings (value, invested, P&L and day change "
        "shown to the user). The figures are no longer in this transcript — "
        "call get_holdings again if you need them."
    )


def _render_money(view: dict) -> str | None:
    kind = view.get("kind")
    # The partial clause sits BEFORE the recovery clause so the stub still ends
    # with something actionable (design shows it trailing; that would break the
    # one property every template must hold).
    partial = (
        " One direction was unavailable for that card."
        if view.get("partial") is True
        else ""
    )
    if kind == "empty":
        return (
            f"{_FRAME} get_money_transactions result cleared. The user had no "
            "money movements this financial year; the empty-state card "
            f"rendered in the chat.{partial} Call get_money_transactions "
            "again if you need the current list."
        )
    if kind != "ok":
        return None
    count = _count(view.get("txns"))
    if count is None:
        return None
    return (
        f"{_FRAME} get_money_transactions result cleared. The money-movements "
        f"card rendered in the chat with {count} pay-in/pay-out transactions "
        f"for the current financial year.{partial} The figures are no longer "
        "in this transcript — call get_money_transactions again if you need "
        "them."
    )


def _render_brokerage(view: dict) -> str | None:
    kind = view.get("kind")
    if kind == "empty":
        return (
            f"{_FRAME} get_brokerage_rates result cleared. No rate card was "
            "available for this client; the empty-state card rendered in the "
            "chat. Call get_brokerage_rates again if you need it."
        )
    if kind != "ok":
        return None
    count = _count(view.get("groups"))
    if count is None:
        return None
    return (
        f"{_FRAME} get_brokerage_rates result cleared. The brokerage rate card "
        f"rendered in the chat with {count} rate groups. The rates are no "
        "longer in this transcript — call get_brokerage_rates again if you "
        "need them."
    )


def _render_file(tool: str, view: dict) -> str | None:
    delivery = view.get("delivery")
    if delivery == "email":
        # NEVER echo emailMasked — the whitelist already dropped it.
        return (
            f"{_FRAME} {tool} result cleared. The report was sent to the "
            "user's registered email, as confirmed in the chat. Call "
            f"{tool} again if the user wants it re-sent."
        )
    if delivery != "download":
        return None
    name = _label((view.get("file") or {}).get("name"))
    what = f"The file {name} was" if name else "The file was"
    return (
        f"{_FRAME} {tool} result cleared. {what} delivered in the chat as a "
        "download card. The download link is no longer in this transcript — "
        f"call {tool} again if the user wants it re-sent."
    )


def _render_kb(view: dict) -> str | None:
    if view.get("kind") != "ok":
        return None
    results = view.get("results")
    if not isinstance(results, list):
        return None
    questions = [
        label
        for item in results
        if isinstance(item, dict)
        and (label := _label(item.get("question"))) is not None
    ]
    if not questions:
        return (
            f"{_FRAME} search_knowledge_base result cleared. The search above "
            "returned no usable support answers. Call search_knowledge_base "
            "again with a different query if the user follows up."
        )
    return (
        f"{_FRAME} search_knowledge_base result cleared, matched questions "
        f"kept. The search above returned {len(results)} support answers, "
        "which you already used in your reply — "
        f"{'; '.join(questions)}. The answer text is no longer in this "
        "transcript — call search_knowledge_base again if the user follows up "
        "on any of them."
    )


def _render_columns(view: dict) -> str | None:
    count = _count(view.get("columns"))
    if count is None:
        return None
    report = _label(view.get("report")) or "requested"
    return (
        f"{_FRAME} get_report_columns result cleared. The column list for the "
        f"{report} report ({count} columns) was returned and you already used "
        "it. The labels are no longer in this transcript — call "
        "get_report_columns again before describing any report column."
    )


def _render_notes(view: dict) -> str | None:
    notes = view.get("notes")
    if not isinstance(notes, list):
        return None
    if not notes:
        return (
            f"{_FRAME} list_contract_notes result cleared. No contract notes "
            "exist for the range in the call above. Call list_contract_notes "
            "again with a different range if the user asks."
        )
    # The list is ascending by trade date, so the newest ids are the tail.
    kept = notes[-_MAX_NOTE_IDS:]
    pairs: list[str] = []
    for note in kept:
        if not isinstance(note, dict):
            continue
        note_id = _label(note.get("id"))
        if note_id is None:
            continue
        parts = [
            part
            for part in (_label(note.get("date")), _label(note.get("segment")))
            if part is not None
        ]
        pairs.append(f"{note_id} = {' '.join(parts)}" if parts else note_id)
    if not pairs:
        return None
    # The ids are opaque, session-bound capability tokens that self-expire
    # (ContractNoteRefStore ttl_seconds=600.0), so they are not PII — but a
    # stale id must never be presented as usable, hence the expiry sentence.
    omitted = (
        " Older ids were dropped — call list_contract_notes again with a "
        "narrower range if the user asks for one of those."
        if len(notes) > _MAX_NOTE_IDS
        else ""
    )
    return (
        f"{_FRAME} list_contract_notes result cleared, ids kept. "
        f"{len(notes)} contract notes were returned for the range in the call "
        "above and offered to the user. Ids for download_contract_note — "
        f"{'; '.join(pairs)}. These ids expire about 10 minutes after they "
        "were issued; if a download bounces, call list_contract_notes again."
        f"{omitted}"
    )


_RENDERERS: dict[str, Callable[[dict], str | None]] = {
    "get_holdings": _render_holdings,
    "get_money_transactions": _render_money,
    "get_brokerage_rates": _render_brokerage,
    "get_pnl_report": lambda view: _render_file("get_pnl_report", view),
    "get_ledger_report": lambda view: _render_file("get_ledger_report", view),
    "get_capital_gains_report": (
        lambda view: _render_file("get_capital_gains_report", view)
    ),
    "download_contract_note": (
        lambda view: _render_file("download_contract_note", view)
    ),
    "search_knowledge_base": _render_kb,
    "get_report_columns": _render_columns,
    "list_contract_notes": _render_notes,
}


# --- class rules + the watermark ---------------------------------------------


def _curatable(turn: Turn) -> bool:
    """The class rules, independent of the watermark: is this turn's tool in a
    class that may ever be stubbed? Opt-in by tool name and fail-open."""
    if getattr(turn, "kind", None) != "tool_result":
        return False
    meta = getattr(turn, "meta", None)
    if not isinstance(meta, dict):
        return False
    if meta.get("is_error") is True:
        return False  # the error text IS the corrective instruction
    name = meta.get("tool_name")
    if not isinstance(name, str) or name in _KEEP_VERBATIM:
        return False
    return name in _RENDERERS  # unregistered => verbatim (fail-open)


def watermark(thread: Thread) -> int:
    """`seq` of the newest `user_text` turn (0 when the thread has none).

    Depends on `user_text` turns ONLY, so it cannot move between rounds of one
    turn: mid-turn appends are `tool_result` and `flow_event`. It is monotone —
    once `seq < W`, always `seq < W` — so a turn is stubbed once and stays
    stubbed, and the curated prefix through the newest user message is
    byte-stable for the life of that watermark."""
    for turn in reversed(getattr(thread, "turns", None) or []):
        if getattr(turn, "kind", None) == "user_text":
            return turn.seq
    return 0


def _render(tool: str, raw: Any) -> str:
    """Stored envelope bytes -> stub text. Never raises: anything unexpected
    degrades to the generic (still actionable) template."""
    try:
        envelope = json.loads(raw) if isinstance(raw, str) else raw
        if not isinstance(envelope, dict):
            return _generic(tool)
        view = _prune(envelope, _ALLOWED_KEYS[tool])
        return _RENDERERS[tool](view) or _generic(tool)
    except Exception:
        return _generic(tool)


def stub_blocks(turn: Turn) -> list[dict[str, Any]] | None:
    """Replacement content blocks for one spent `tool_result` turn, or None to
    keep the stored bytes verbatim.

    Only the `tool_result` **`content`** string is replaced; `type`,
    `tool_use_id` and `is_error` are copied through, so every `tool_use` block
    still has exactly one matching `tool_result`. Returns fresh dicts — no
    stored block is mutated or aliased. Never raises."""
    try:
        if not _curatable(turn):
            return None
        tool = turn.meta["tool_name"]
        blocks: list[dict[str, Any]] = []
        for block in turn.content:
            if not isinstance(block, dict):
                return None  # not a content-block array we understand
            stub = dict(block)
            if block.get("type") == "tool_result":
                stub["content"] = _render(tool, block.get("content"))
            blocks.append(stub)
        return blocks or None
    except Exception:  # pragma: no cover — belt and braces; must never raise
        return None


# --- the projection ----------------------------------------------------------


def curate(thread: Thread) -> Callable[[Turn], list[dict[str, Any]] | None]:
    """The `transform` closure for `Thread.messages(transform=...)`.

    Stubs are memoised per `turn.seq` in the non-persisted `thread.curated`
    dict (precedent: `first_name` / `name_fetched`). Memoisation is sound
    because the watermark is monotone and the stub text is a pure function of
    stored bytes. Each call hands back fresh dicts so nothing downstream can
    reach into the cache — or into the store."""
    mark = watermark(thread)
    cache = thread.curated

    def transform(turn: Turn) -> list[dict[str, Any]] | None:
        if turn.seq >= mark:
            return None  # K=1: the current turn's results stay verbatim
        blocks = cache.get(turn.seq)
        if blocks is None:
            blocks = stub_blocks(turn)
            if blocks is None:
                return None
            cache[turn.seq] = blocks
        return [dict(block) for block in blocks]

    return transform


def messages_for_model(thread: Thread) -> list[dict[str, Any]]:
    """The curated model-facing messages array. The store is untouched:
    `thread.messages()` with no transform still returns the lossless bytes."""
    return thread.messages(transform=curate(thread))


# --- observability (counts only — never text) --------------------------------


def curated_turn_count(thread: Thread) -> int:
    """How many stored `tool_result` turns the projection stubs. Pure; safe to
    call with the flag off (the loop then reports 0)."""
    mark = watermark(thread)
    return sum(
        1
        for turn in (getattr(thread, "turns", None) or [])
        if turn.seq < mark and _curatable(turn)
    )


def history_tokens_est(messages: list[dict[str, Any]]) -> int:
    """~4-chars-per-token estimate over the assembled history, for the `llm`
    trace span. A COUNT for operators — no message text is retained anywhere.
    Verify against `agent_traces.input_tokens` after the flag flip."""
    try:
        return len(json.dumps(messages, separators=(",", ":"), default=str)) // 4
    except Exception:  # pragma: no cover — estimate must never break a turn
        return 0
