"""Flow events — widget completions bridged into agent memory (CHO-214 · D4/D5).

When a deterministic report endpoint resolves — a success, or a no-data
result (CHO-253) — it records a `flow_event` turn on the session's thread so
the agent remembers what the widget did ("now the same for F&O" works) and
knows when a prior attempt came back empty. The write is fire-and-forget: memo built
synchronously (deterministic), thread lookup + enqueue in a background task
that swallows every failure — the report response is never delayed and never
fails because of memory.

The memo is the exact text the model later receives (stored content == wire
content, keeping the store's byte-faithful replay invariant). It is framed
as an app event so the model reads it as data, not user prose, and carries
only the customer-facing labels the UI showed plus ISO dates the model can
re-seed follow-ups from. Never credentials, tokens, or upstream fields.
"""

import asyncio
import datetime
import logging
from typing import Any

logger = logging.getLogger("app.agent.events")

_FRAME = "[App event — generated by the app, not typed by the user]"

_FLOW_NAMES = {
    "pnl": "P&L",
    "ledger": "ledger",
    "tax": "capital gains",
    "contract-notes": "contract note",
}

_OUTCOMES = {
    "download": "downloaded successfully",
    "email": "sent to the registered email",
}

_MON = (
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
)


def friendly_range(from_iso: str, to_iso: str) -> str:
    """"1 Jun – 30 Jun 2026 (2026-06-01 → 2026-06-30)" — human label first,
    ISO pair second so follow-up seeding needs no date math."""
    try:
        f = datetime.date.fromisoformat(from_iso)
        t = datetime.date.fromisoformat(to_iso)
    except ValueError:
        return f"{from_iso} → {to_iso}"
    if f.year == t.year:
        label = f"{f.day} {_MON[f.month - 1]} – {t.day} {_MON[t.month - 1]} {t.year}"
    else:
        label = (
            f"{f.day} {_MON[f.month - 1]} {f.year} – "
            f"{t.day} {_MON[t.month - 1]} {t.year}"
        )
    return f"{label} ({from_iso} → {to_iso})"


def render_memo(flow: str, details: list[str], delivery: str) -> str:
    """The deterministic app-event memo (design D4). `details` are the
    customer-facing slot labels in flow order."""
    name = _FLOW_NAMES.get(flow, flow)
    outcome = _OUTCOMES.get(delivery, delivery)
    filled = f": {', '.join(details)}" if details else ""
    return (
        f"{_FRAME} The user completed the {name} form in the "
        f"widget{filled} — {outcome}."
    )


def render_no_data_memo(flow: str, details: list[str]) -> str:
    """The no-data app-event memo (CHO-253): the user completed the form but
    the report came back empty for that selection — so the model's next reply
    can reason about the miss instead of being blind to it."""
    name = _FLOW_NAMES.get(flow, flow)
    filled = f": {', '.join(details)}" if details else ""
    return (
        f"{_FRAME} The user requested the {name} report in the "
        f"widget{filled} — no records were found for that selection."
    )


def record_flow_event(
    app: Any,
    *,
    session_id: str,
    client_code: str | None,
    flow: str,
    details: list[str],
    slots: dict[str, Any],
    delivery: str,
    outcome: str = "success",
) -> None:
    """Fire-and-forget: enqueue the flow_event turn on the session's thread.
    Safe to call from any route — no store, no running loop, or any failure
    just skips the event (length-only logging).

    `outcome` is "success" for a delivered report or "no_data" when the report
    came back empty (CHO-253); the memo and meta reflect which."""
    store = getattr(getattr(app, "state", None), "conversation_store", None)
    if store is None:
        return
    memo = (
        render_memo(flow, details, delivery)
        if outcome == "success"
        else render_no_data_memo(flow, details)
    )
    meta = {
        "flow": flow,
        "slots": slots,
        "delivery": delivery,
        "outcome": outcome,
    }

    async def _record() -> None:
        try:
            thread = await store.get_thread(session_id, client_code=client_code)
            store.append_turn(
                thread,
                role="user",
                kind="flow_event",
                content=[{"type": "text", "text": memo}],
                meta=meta,
            )
        except Exception as exc:
            logger.warning("flow event dropped error=%s", type(exc).__name__)

    try:
        asyncio.get_running_loop().create_task(_record())
    except RuntimeError:  # no running loop (sync test context) — skip
        logger.warning("flow event dropped error=NoRunningLoop")
